{"component":"brat","action":"config.interpolate","vars_used":["DOMAIN_SUFFIX","ENV_PREFIX"],"unresolved":[],"notice":"Set BITBRAT_INTERPOLATION=0 to disable interpolation temporarily"}
architecture:
  name: BitBrat Platform
  defaults:
    services:
      implementation: cloud-run
      runtime:
        node: 24.x
      region: us-central1
      network: bitbrat-prod-vpc
      scaling:
        min: 1
        max: 1
      observability:
        log_export: cloud-logging
        metrics: cloud-monitoring
      port: 3000
      health:
        - /healthz
        - /readyz
        - /livez
      topics:
        publishes:
          - internal.finalize.v1
      security:
        allowUnauthenticated: true
      env:
        - LOG_LEVEL
        - MESSAGE_BUS_DRIVER
        - NATS_URL
        - BUS_PREFIX
  services:
    oauth-flow:
      active: true
      description: >-
        OAuth2 authentication service that handles Streaming Platform OAuth2
        flow for bot and broadcaster accounts.
      entry: src/apps/oauth-service.ts
      scaling:
        min: 0
        max: 1
      secrets:
        - TWITCH_CLIENT_ID
        - TWITCH_CLIENT_SECRET
        - OAUTH_STATE_SECRET
    ingress-egress:
      active: true
      description: >-
        Bridges external event sources/sinks (e.g., Twitch EventSub/IRC) to
        internal topics;
      entry: src/apps/ingress-egress-service.ts
      env:
        - TWITCH_BOT_USERNAME
        - TWITCH_CHANNELS
        - K_REVISION
      secrets:
        - TWITCH_CLIENT_ID
        - TWITCH_CLIENT_SECRET
    auth:
      active: true
      description: >-
        Authentication service that handles user authentication and
        authorization.
      entry: src/apps/auth-service.ts
      secrets:
        - TWITCH_CLIENT_ID
        - TWITCH_CLIENT_SECRET
    event-router:
      active: true
      description: >-
        Internal event routing service that reads from ingress channel(s) and
        assigns routing slips.
      entry: src/apps/event-router-service.ts
    llm-bot:
      active: true
      description: >-
        Headless LLM worker that consumes bot request subjects and produces
        responses.
      entry: src/apps/llm-bot-service.ts
      env:
        - OPENAI_MODEL
        - OPENAI_TIMEOUT_MS
        - OPENAI_MAX_RETRIES
      secrets:
        - OPENAI_API_KEY
    finalizer:
      active: false
      description: >-
        Finalizer service logs the final state of a message and makes sure any
        open requests are responded to.
      entry: src/apps/finalizer-service.ts
    command-processor:
      active: true
      description: >-
        Command processor service handles incoming commands and executes them,
        producing responses.
      entry: src/apps/command-processor-service.ts
      env:
        - BOT_USERNAME
  deploymentDefaults:
    maxConcurrentDeployments: 1
    region: us-central1
    cloud-run:
      platform: managed
      minInstances: 0
      maxInstances: 100
      cpu: '1'
      memory: 512Mi
  infrastructure:
    target: gcp
    resources:
      default-content-bucket:
        type: object-store
        implementation: cloud-storage
        description: Static assets for the default website.
        access_policy: private
      main-load-balancer:
        type: load-balancer
        implementation: global-external-application-lb
        name: bitbrat-platform-lb
        ip: bitbrat-platform-ip
        description: Main external entry point and router for the application
        routing:
          default_domain: api.bitbrat.ai
          default_bucket: default-content-bucket
          rules:
            - path_prefix: /assets
              bucket: default-content-bucket
            - path_prefix: /oauth
              service: oauth-flow
            - path_prefix: /_debug/ingress/twitch
              rewrite_prefix: /_debug/twitch
              service: ingress-egress
            - path_prefix: /_debug/ingress/config
              rewrite_prefix: /_debug/config
              service: ingress-egress
  description: >-
    The BitBrat Platform is an LLM powered event orchestration and execution
    engine aimed at Streamers. Uses Node/TypeScript, Twurple, Firestore, OpenAI,
    oshuaalpuerto/mcp-agent. Deployed on Cloud Run.
  project:
    name: BitBrat Platform
    version: 0.1.0
    description: >
      A cloud-native microservices suite that listens to Twitch, Kick and other
      events and provides tools to react to them.
    owners:
      - chris@ix-n.com
  llm_guidance:
    default_system_prompt: >
      You are an experienced Staff Engineer responsible fpr developing the
      BitBrat Platform. Follow the architecture.yaml specs strictly. Justify any
      architectural deviation clearly.
services:
  oauth-flow:
    name: oauth-flow
    region: us-central1
    port: 3000
    minInstances: 0
    maxInstances: 1
    cpu: '1'
    memory: 512Mi
    allowUnauth: true
    envKeys:
      - LOG_LEVEL
      - MESSAGE_BUS_DRIVER
      - NATS_URL
      - BUS_PREFIX
    secrets:
      - TWITCH_CLIENT_ID
      - TWITCH_CLIENT_SECRET
      - OAUTH_STATE_SECRET
  ingress-egress:
    name: ingress-egress
    region: us-central1
    port: 3000
    minInstances: 1
    maxInstances: 1
    cpu: '1'
    memory: 512Mi
    allowUnauth: true
    envKeys:
      - LOG_LEVEL
      - MESSAGE_BUS_DRIVER
      - NATS_URL
      - BUS_PREFIX
      - TWITCH_BOT_USERNAME
      - TWITCH_CHANNELS
      - K_REVISION
    secrets:
      - TWITCH_CLIENT_ID
      - TWITCH_CLIENT_SECRET
  auth:
    name: auth
    region: us-central1
    port: 3000
    minInstances: 1
    maxInstances: 1
    cpu: '1'
    memory: 512Mi
    allowUnauth: true
    envKeys:
      - LOG_LEVEL
      - MESSAGE_BUS_DRIVER
      - NATS_URL
      - BUS_PREFIX
    secrets:
      - TWITCH_CLIENT_ID
      - TWITCH_CLIENT_SECRET
  event-router:
    name: event-router
    region: us-central1
    port: 3000
    minInstances: 1
    maxInstances: 1
    cpu: '1'
    memory: 512Mi
    allowUnauth: true
    envKeys:
      - LOG_LEVEL
      - MESSAGE_BUS_DRIVER
      - NATS_URL
      - BUS_PREFIX
    secrets: []
  llm-bot:
    name: llm-bot
    region: us-central1
    port: 3000
    minInstances: 1
    maxInstances: 1
    cpu: '1'
    memory: 512Mi
    allowUnauth: true
    envKeys:
      - LOG_LEVEL
      - MESSAGE_BUS_DRIVER
      - NATS_URL
      - BUS_PREFIX
      - OPENAI_MODEL
      - OPENAI_TIMEOUT_MS
      - OPENAI_MAX_RETRIES
    secrets:
      - OPENAI_API_KEY
  finalizer:
    name: finalizer
    region: us-central1
    port: 3000
    minInstances: 1
    maxInstances: 1
    cpu: '1'
    memory: 512Mi
    allowUnauth: true
    envKeys:
      - LOG_LEVEL
      - MESSAGE_BUS_DRIVER
      - NATS_URL
      - BUS_PREFIX
    secrets: []
  command-processor:
    name: command-processor
    region: us-central1
    port: 3000
    minInstances: 1
    maxInstances: 1
    cpu: '1'
    memory: 512Mi
    allowUnauth: true
    envKeys:
      - LOG_LEVEL
      - MESSAGE_BUS_DRIVER
      - NATS_URL
      - BUS_PREFIX
      - BOT_USERNAME
    secrets: []
maxConcurrency: 1
regionDefault: us-central1

