name: BitBrat Platform
description: The BitBrat Platform is an LLM powered event orchestration and execution engine aimed at Streamers. Uses Node/TypeScript, Twurple,
  Firestore, OpenAI. Deployed on Cloud Run.
project:
  name: BitBrat Platform
  version: 0.1.0
  description: |
    A cloud-native microservices suite that listens to Twitch, Kick and other events and provides tools to react to them.
  owners:
    - chris@ix-n.com
llm_guidance:
  default_system_prompt: >
    You are an experienced Staff Engineer responsible for developing the BitBrat Platform.
    Follow the architecture.yaml specs strictly. Justify any architectural deviation clearly.

defaults: # Defaults for various entities. Individual entities may override these.
  services: # Default settings for all services
    implementation: cloud-run # What sort of cloud resource to use by default to provision for this service
    runtime: # Default runtime to use for services
      node: 24.x
    region: us-central1 # Default region to use for services
    network: bitbrat-prod-vpc # Default VPC to deploy services to
    scaling: # Default scaling rules for services
      min: 1
      max: 1
    observability:
      log_export: cloud-logging
      metrics: cloud-monitoring
      tracing:
        enabled: false         # TRACING_ENABLED default
        sampler_ratio: 0.1     # TRACING_SAMPLER_RATIO default
    port: 3000
    health: # Default HTTP-based health check endpoints for services
      - /healthz
      - /readyz
      - /livez
    topics:
      publishes:
        - internal.finalize.v1 # All services may finalize a message
    security:
      allowUnauthenticated: true # Allow unauthenticated traffic to the service
    env: # Environment variables required by all services
      - LOG_LEVEL
      - MESSAGE_BUS_DRIVER
      - NATS_URL
      - BUS_PREFIX

services:
  oauth-flow:
    active: true
    description: "OAuth2 authentication service that handles Streaming Platform OAuth2 flow for bot and broadcaster accounts."
    entry: src/apps/oauth-service.ts
    scaling:
      min: 0
      max: 1
    paths:
      - /oauth/*
    secrets:
      - TWITCH_CLIENT_ID
      - TWITCH_CLIENT_SECRET
      - OAUTH_STATE_SECRET
      # Discord OAuth (user-level flows optional; prep for future)
      - DISCORD_CLIENT_ID
      - DISCORD_CLIENT_SECRET
    env:
      - DISCORD_REDIRECT_URI
      - DISCORD_OAUTH_SCOPES
      - DISCORD_OAUTH_PERMISSIONS
      - TWITCH_OAUTH_SCOPES

  ingress-egress:
    active: true
    description: "Bridges external event sources/sinks (e.g., Twitch EventSub/IRC) to internal topics;"
    entry: src/apps/ingress-egress-service.ts
    topics:
      publishes:
        - internal.ingress.v1
      consumes:
        # Per-instance egress topic subscription. The service resolves {instanceId} at runtime
        # using K_REVISION || EGRESS_INSTANCE_ID || SERVICE_INSTANCE_ID || HOSTNAME || generated id
        - internal.egress.v1.{instanceId}
        - internal.egress.v1
    paths:
      - /_debug/twitch # Debug endpoint that displays the current state of the Twitch IRC and EventSub connections
      - /_debug/discord # Debug endpoint for Discord connection state
      - /_debug/twilio # Debug endpoint for Twilio Conversations state
      - /webhooks/twilio # Twilio webhook for conversation lifecycle events
    secrets:
      - TWITCH_CLIENT_ID
      - TWITCH_CLIENT_SECRET
      - DISCORD_BOT_TOKEN
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
      - TWILIO_API_KEY
      - TWILIO_API_SECRET
      - TWILIO_CHAT_SERVICE_SID
    env:
      - TWITCH_BOT_USERNAME
      - TWITCH_CHANNELS
      # Discord configuration and rollout flags
      - DISCORD_ENABLED
      # Twilio configuration
      - TWILIO_ENABLED
      # Optional instance identity for per-instance egress topic.
      # The service resolves instanceId via: K_REVISION || EGRESS_INSTANCE_ID || SERVICE_INSTANCE_ID || HOSTNAME || generated
      # Only K_REVISION is listed here because it is auto-provided by Cloud Run when present.
      # EGRESS_INSTANCE_ID and SERVICE_INSTANCE_ID are SUPPORTED but OPTIONAL and therefore not required here.
      - K_REVISION

  auth:
    active: true
    description: "Authentication service that handles user authentication and authorization."
    entry: src/apps/auth-service.ts
    topics:
      publishes:
        - internal.user.enriched.v1
      consumes:
        - internal.ingress.v1
    secrets:
      - TWITCH_CLIENT_ID
      - TWITCH_CLIENT_SECRET
      - MCP_AUTH_TOKEN

  event-router:
    active: true
    description: "Internal event routing service that reads from ingress channel(s) and assigns routing slips."
    entry: src/apps/event-router-service.ts
    topics:
      publishes:
        - internal.llmbot.v1
      consumes:
        - internal.user.enriched.v1

  llm-bot:
    active: true
    description: "Headless LLM worker that consumes bot request subjects and produces responses."
    entry: src/apps/llm-bot-service.ts
    paths:
      - /_debug/mcp # Debug endpoint that displays the current state of the MCP servers
    topics:
      consumes:
        - internal.llmbot.v1
    secrets:
      - OPENAI_API_KEY
    env:
      - OPENAI_MODEL
      - OPENAI_TIMEOUT_MS
      - OPENAI_MAX_RETRIES
      # Short-term memory bounds (in-run)
      - LLM_BOT_MEMORY_MAX_MESSAGES
      - LLM_BOT_MEMORY_MAX_CHARS
      # Optional system primer for conversations (prepended once when memory empty)
      - LLM_BOT_SYSTEM_PROMPT
      # Instance-scoped short-term memory (cross-event within process lifetime)
      - LLM_BOT_INSTANCE_MEM_MAX_KEYS
      - LLM_BOT_INSTANCE_MEM_MAX_MSGS
      - LLM_BOT_INSTANCE_MEM_MAX_CHARS
      - LLM_BOT_INSTANCE_MEM_TTL_MS

  persistence:
    active: true
    description: "Persists and indexes events for later retrieval"
    entry: src/apps/persistence-service.ts
    topics:
      consumes:
        - internal.ingress.v1
        - internal.persistence.finalize.v1
        - internal.deadletter.v1
        - internal.router.dlq.v1

  obs-mcp:
    active: true
    description: MCP server for controlling OBS
    image: us-central1-docker.pkg.dev/bitbrat-local/obs-mcp/obs-mcp:latest
    env:
      - MCP_TRANSPORT
      - OBS_WEBSOCKET_URL
      - OBS_WEBSOCKET_SELF_SIGNED
    secrets:
      - OBS_WEBSOCKET_PASSWORD
      - MCP_AUTH_TOKEN

  scheduler:
    active: true
    description: Scheduler service for periodic tasks
    entry: src/apps/scheduler-service.ts
    topics:
      publishes:
        - internal.ingress.v1
      consumes:
        - internal.scheduler.tick
    secrets:
      - MCP_AUTH_TOKEN

  api-gateway:
    description: API Gateway for handling incoming requests and routing them to appropriate services
    entry: src/apps/api-gateway.ts
    topics:
      publishes:
        - internal.ingress.v1
      consumes:
        # Per-instance egress topic subscription. The service resolves {instanceId} at runtime
        # using K_REVISION || EGRESS_INSTANCE_ID || SERVICE_INSTANCE_ID || HOSTNAME || generated id
        - internal.api.egress.v1.{instanceId}
        - internal.egress.v1

  query-analyzer:
    description: Executes fast, efficient pre-analysis of incoming events to better route and respond
    entry: src/apps/query-analyzer.ts
    topics:
      consumes:
        - internal.query.analysis.v1

infrastructure:
  target: gcp
  resources:
    default-content-bucket:
      type: object-store
      implementation: cloud-storage
      description: Static assets for the default website.
      access_policy: private

    main-load-balancer:
      type: load-balancer
      implementation: global-external-application-lb
      name:  bitbrat-platform-lb
      ip: bitbrat-platform-ip
      cert: bitbrat-${ENV}-cert
      https_redirect: true
      description: Main external entry point and router for the application
      routing:
        default_bucket: default-content-bucket
        default_domain: ${DOMAIN_PREFIX}${ENV_PREFIX}${DOMAIN_SUFFIX:-bitbrat.ai}
        rules:
          # Static Assets Routing
          - path_prefix: /assets
            bucket: default-content-bucket

          # OAuth Routing
          - path_prefix: /oauth
            service: oauth-flow

          # API Gateway (WebSocket)
          - path_prefix: /ws/v1
            service: api-gateway

          # Debug Routes
          - path_prefix: /_debug/ingress/twitch
            rewrite_prefix: /_debug/twitch
            service: ingress-egress
          - path_prefix: /_debug/ingress/config
            rewrite_prefix: /_debug/config
            service: ingress-egress
          - path_prefix: /_debug/ingress/twilio
            rewrite_prefix: /_debug/twilio
            service: ingress-egress
          - path_prefix: /_debug/ingress/discord
            rewrite_prefix: /_debug/discord
            service: ingress-egress
          - path_prefix: /_debug/llm/mcp
            rewrite_prefix: /_debug/mcp
            service: llm-bot

          # Twilio Webhook
          # Configuration Note: In Twilio Console, ensure both 'onConversationAdded' AND 'onMessageAdded'
          # are enabled in the Service-level Post-event Webhooks.
          - path_prefix: /webhooks/twilio
            service: ingress-egress

    internal-load-balancer:
      type: load-balancer
      implementation: regional-internal-application-lb
      name: bitbrat-internal-lb
      ip: bitbrat-internal-ip
      description: Internal load balancer for service-to-service communication
      routing:
        default_domain: bitbrat.local
        rules:
          - path_prefix: /
            service: llm-bot
          - path_prefix: /
            service: auth
          - path_prefix: /
            service: oauth-flow
          - path_prefix: /
            service: ingress-egress
          - path_prefix: /
            service: event-router
          - path_prefix: /
            service: persistence
          - path_prefix: /
            service: command-processor
          - path_prefix: /
            service: obs-mcp
          - path_prefix: /
            service: scheduler

deploymentDefaults:
  maxConcurrentDeployments: 3
  region: us-central1
  cloud-run:
    platform: managed
    minInstances: 1
    maxInstances: 1
    cpu: '1'
    memory: 512Mi
    # Ensure all services use instance-based billing by default
    billing: instance
  global-external-application-lb:
    loadBalancingScheme: EXTERNAL_MANAGED

# Networking posture (Sprint 113):
# - No Cloud NAT: outbound public traffic should use Cloud Run default egress path for best latency.
# - VPC connectors are used to reach private RFC1918 ranges only; services should configure
#   egress: PRIVATE_RANGES_ONLY when attaching a Serverless VPC Access connector.
# - Subnets keep private_ip_google_access = true; PSC/restricted VIP for Google APIs is not required now.
