options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE
substitutions:
  _SERVICE_NAME: oauth-flow
  _REGION: us-central1
  _REPO_NAME: bitbrat-services
  _DRY_RUN: 'true'
  _TAG: 'manual'
  _PORT: '3000'
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '3'
  _CPU: '1'
  _MEMORY: '512Mi'
  _ALLOW_UNAUTH: 'true'
  _SECRET_SET_ARG: ''
  _ENV_VARS_ARG: ''
  _DOCKERFILE: 'Dockerfile.oauth-flow'
  # Billing model: ensure instance-based billing on Cloud Run
  _BILLING: 'instance'
  # Networking: enforce Internal & CLB ingress and attach VPC connector when provided
  _INGRESS: 'internal-and-cloud-load-balancing'
  _VPC_CONNECTOR: ''
steps:
  - id: 'Install deps'
    name: 'gcr.io/cloud-builders/npm'
    args: ['ci']

  - id: 'Run unit tests'
    name: 'gcr.io/cloud-builders/npm'
    args: ['test', '--', '--ci', '--reporters=default']

  - id: 'Build (tsc)'
    name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  - id: 'Docker build'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - '${_DOCKERFILE}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:${_TAG}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:latest'
      - '.'

  - id: 'Docker push ${_TAG}'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:${_TAG}'

  - id: 'Docker push latest'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:latest'

  - id: 'Cloud Run deploy (conditional)'
    # Pin to a specific, recent version of the Cloud SDK to ensure all flags are available.
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:478.0.0'
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -euo pipefail
        IMAGE="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:${_TAG}"
        echo "--- Using gcloud version: ---"
        gcloud --version
        if [ "${_DRY_RUN}" = "true" ]; then
          echo "_DRY_RUN=true: skipping gcloud run deploy. Image available at $$IMAGE"
          exit 0
        fi
        echo "Cloud Run deploy parameters:"
        echo "  service: ${_SERVICE_NAME}"
        echo "  region: ${_REGION}"
        echo "  port: ${_PORT}"
        echo "  min-instances: ${_MIN_INSTANCES}"
        echo "  max-instances: ${_MAX_INSTANCES}"
        echo "  cpu: ${_CPU}"
        echo "  memory: ${_MEMORY}"
        echo "  billing: ${_BILLING}"
        echo "  ingress: ${_INGRESS}"
        echo "  vpc-connector: ${_VPC_CONNECTOR}"
        ALLOW_FLAG=""
        if [ "${_ALLOW_UNAUTH}" = "true" ]; then
          ALLOW_FLAG="--allow-unauthenticated"
        fi

        # Build command as a string to ensure correct parsing by the shell
        CMD="gcloud run deploy ${_SERVICE_NAME} \
          --image $$IMAGE \
          --region ${_REGION} \
          --platform managed \
          --port ${_PORT} \
          --min-instances ${_MIN_INSTANCES} \
          --max-instances ${_MAX_INSTANCES} \
          --cpu ${_CPU} --memory ${_MEMORY} \
          --execution-environment gen2 \
          --no-cpu-throttling"

        if [ -n "${_INGRESS}" ]; then CMD="$${CMD} --ingress ${_INGRESS}"; fi
        if [ -n "${_VPC_CONNECTOR}" ]; then CMD="$${CMD} --vpc-connector ${_VPC_CONNECTOR}"; fi
        if [ -n "$$ALLOW_FLAG" ]; then CMD="$${CMD} $$ALLOW_FLAG"; fi
        if [ -n "${_SECRET_SET_ARG}" ]; then CMD="$${CMD} --set-secrets $(printf '%s' "${_SECRET_SET_ARG}" | tr ';' ',')"; fi
        # Use a custom delimiter for --set-env-vars so values may contain commas and spaces without breaking parsing
        # Format: --set-env-vars='^<DELIM>^KEY=VAL<DELIM>KEY2=VAL2'
        if [ -n "${_ENV_VARS_ARG}" ]; then
          ENV_DELIM='~'
          # Convert our semicolon-delimited KV list to the chosen delimiter; wrap in single quotes to preserve spaces
          ENV_MAPPED=$(printf '%s' "${_ENV_VARS_ARG}" | tr ';' "$$ENV_DELIM")
          SET_ENV_ARG="^$$ENV_DELIM^$$ENV_MAPPED"
          CMD="$${CMD} --set-env-vars='$$SET_ENV_ARG'"
        fi

        echo "Executing: $$CMD"
        eval "$$CMD"

        # Explicitly ensure IAM binding for unauthenticated access when requested
        if [ "${_ALLOW_UNAUTH}" = "true" ]; then
          echo "Ensuring roles/run.invoker binding for allUsers on service ${_SERVICE_NAME}"
          gcloud run services add-iam-policy-binding "${_SERVICE_NAME}" \
            --region "${_REGION}" \
            --member "allUsers" \
            --role "roles/run.invoker"
        fi
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:${_TAG}'
