/**
 * Template generators for brat bit create command
 * Sprint 331: BL-331-103
 */

/**
 * Interface for template generation options
 */
export interface TemplateOptions {
  name: string;
  profile: 'core' | 'gateway' | 'llm' | 'mcp-domain';
  exposure: 'platform-only' | 'platform+domain' | 'none';
  kind: 'pipeline-service' | 'gateway' | 'mcp-server';
  port?: number;
  entry?: string;
  paths?: string[];
  consumes?: string[];
}

/**
 * Converts kebab-case to PascalCase
 */
function toPascal(name: string): string {
  const parts = String(name)
    .trim()
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1).toLowerCase());
  return parts.join('');
}

/**
 * Generates the main application source file
 */
export function generateAppSource(opts: TemplateOptions): string {
  const className = `${toPascal(opts.name)}Server`;
  const serviceName = opts.name;

  // Determine super constructor argument based on exposure
  let superArg = '';
  if (opts.exposure === 'platform-only') {
    superArg = "{ mcpExposure: 'platform-only' }";
  } else if (opts.exposure === 'platform+domain') {
    superArg = "{ mcpExposure: 'platform+domain' }";
  }
  // If exposure is 'none', superArg remains empty string

  // Determine imports based on profile
  const needsExpress = opts.profile === 'gateway' || (opts.paths && opts.paths.length > 0);
  const needsZod = opts.profile === 'mcp-domain';

  const expressImport = needsExpress ? "import { Request, Response } from 'express';\n" : "";
  const zodImport = needsZod ? "import { z } from 'zod';\n" : "";

  // Generate profile-specific setup method content
  let setupContent = '';

  if (opts.profile === 'gateway' || (opts.paths && opts.paths.length > 0)) {
    // Gateway profile: include HTTP route examples
    const explicitHandlers = opts.paths && opts.paths.length > 0
      ? opts.paths.map((p) => `    app.get('${p}', (_req: Request, res: Response) => { res.status(200).json({ message: 'OK' }); });`).join('\n')
      : '    // Add your HTTP routes here';

    setupContent = `  private setupRoutes() {
    const app = this.getApp();
${explicitHandlers}

    // Health check
    app.get('/health', (_req: Request, res: Response) => {
      res.status(200).json({ status: 'ok', service: '${serviceName}' });
    });
  }`;
  }

  if (opts.profile === 'mcp-domain') {
    // MCP-domain profile: include MCP tool registration example
    setupContent = `  private registerDomainTools() {
    // Example MCP tool registration
    this.registerTool(
      'echo',
      'Echoes back the input message',
      z.object({
        message: z.string().describe('The message to echo'),
      }),
      async (args) => {
        return {
          content: [{ type: 'text', text: args.message }],
        };
      }
    );

    // Add more tools here as needed
  }`;
  }

  if (opts.profile === 'llm') {
    // LLM profile: include provider initialization comment
    setupContent = `  private async setupLLM() {
    // TODO: Initialize LLM provider (OpenAI, Ollama, vLLM, etc.)
    // Example:
    // const llmProvider = this.getConfig('LLM_PROVIDER') || 'openai';
    // this.logger.info({ provider: llmProvider }, 'LLM provider initialized');
  }`;
  }

  // Generate constructor content
  let constructorContent = `  constructor() {
    super(${superArg});`;

  if (opts.profile === 'gateway' || (opts.paths && opts.paths.length > 0)) {
    constructorContent += `\n    this.setupRoutes();`;
  }

  if (opts.profile === 'mcp-domain') {
    constructorContent += `\n    this.registerDomainTools();`;
  }

  if (opts.profile === 'llm') {
    constructorContent += `\n    // Call setupLLM() if needed during initialization`;
  }

  constructorContent += `\n  }`;

  // Generate the full source
  return `${expressImport}${zodImport}import { Bit } from '../common/base-server';

/**
 * ${className}
 * Generated by brat bit create (Sprint 331)
 * Profile: ${opts.profile}
 * MCP Exposure: ${opts.exposure}
 * Kind: ${opts.kind}
 */
export class ${className} extends Bit {
${constructorContent}

${setupContent ? setupContent + '\n' : ''}
  public async close(reason: string = 'manual'): Promise<void> {
    await super.close(reason);
  }
}

if (require.main === module) {
  const server = new ${className}();
  const port = parseInt(process.env.PORT || '${opts.port || 3000}', 10);
  server.start(port).catch((err) => {
    console.error('Failed to start ${serviceName}:', err);
    process.exit(1);
  });
}
`;
}

/**
 * Generates the unit test file
 */
export function generateTest(name: string, entry: string): string {
  const className = `${toPascal(name)}Server`;
  const entryFilename = entry.replace(/^src\//, '').replace(/\.ts$/, '');

  return `import request from 'supertest';
import { ${className} } from './${entryFilename.split('/').pop()}';

describe('${name}', () => {
  let server: ${className};

  beforeAll(async () => {
    server = new ${className}();
    // Server starts automatically via constructor
  });

  afterAll(async () => {
    await server.close('test');
  });

  it('should respond to health check', async () => {
    const response = await request(server.getApp()).get('/healthz');
    expect(response.status).toBe(200);
    expect(response.body.status).toBe('ok');
  });
});
`;
}

/**
 * Generates the Dockerfile
 */
export function generateDockerfile(name: string, entry: string): string {
  const entryJs = entry.replace(/^src\//, '').replace(/\.ts$/, '.js');

  return `FROM node:24-slim AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:24-slim
WORKDIR /app
COPY package*.json ./
RUN npm ci --production
COPY --from=builder /app/dist ./dist
COPY architecture.yaml ./

ENV NODE_ENV=production
ENV SERVICE_NAME=${name}

CMD ["node", "dist/${entryJs}"]
`;
}

/**
 * Generates the docker-compose service definition
 */
export function generateCompose(
  name: string,
  port: number,
  env: string[],
  secrets: string[]
): string {
  const upperName = name.toUpperCase().replace(/-/g, '_');
  const allVars = [...env, ...secrets];
  const envLines = allVars.length > 0
    ? '\n' + allVars.map(v => `      - ${v}=\${${v}}`).join('\n')
    : '';

  return `services:
  ${name}:
    build:
      context: .
      dockerfile: Dockerfile.${name}
    ports:
      - "\${${upperName}_HOST_PORT:-${port}}:${port}"
    environment:
      - NODE_ENV=local
      - BITBRAT_ENV=local
      - PORT=${port}${envLines}
    env_file:
      - .env.brat
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${port}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      nats:
        condition: service_healthy
      firebase-emulator:
        condition: service_healthy
    networks:
      - bitbrat-network

networks:
  bitbrat-network:
    external: true
`;
}
