#!/bin/bash
# MCP SDK 2.0 Migration Rollback Script
# Sprint: sprint-28-kbuirw
# Purpose: Quick rollback to v1.x if critical issues arise

set -e

echo "=== MCP SDK 2.0 Migration Rollback ==="
echo ""

# Get context from environment or default
CONTEXT="${1:-staging}"

echo "⚠️  WARNING: This will rollback the MCP SDK 2.0 migration"
echo "Context: $CONTEXT"
echo ""

# Safety check
if [ "$CONTEXT" = "production" ] && [ "$CONFIRM_PROD_ROLLBACK" != "yes" ]; then
  echo "❌ Production rollback requires CONFIRM_PROD_ROLLBACK=yes"
  echo "Usage: CONFIRM_PROD_ROLLBACK=yes bash rollback.sh production"
  exit 1
fi

# Ask for confirmation
read -p "Continue with rollback? (yes/no): " CONFIRM
if [ "$CONFIRM" != "yes" ]; then
  echo "Rollback cancelled"
  exit 0
fi

echo ""
echo "Step 1: Reverting git changes..."
# Find the commit before the migration
MIGRATION_COMMIT=$(git log --oneline --grep="Sprint 28.*MCP SDK 2.0" | head -1 | awk '{print $1}')

if [ -z "$MIGRATION_COMMIT" ]; then
  echo "  ⚠️  Migration commit not found. Finding by file changes..."
  MIGRATION_COMMIT=$(git log --oneline --all -S "@modelcontextprotocol/server" | head -1 | awk '{print $1}')
fi

if [ -z "$MIGRATION_COMMIT" ]; then
  echo "  ❌ Cannot find migration commit. Manual rollback required."
  exit 1
fi

PREVIOUS_COMMIT="${MIGRATION_COMMIT}^"
echo "  Migration commit: $MIGRATION_COMMIT"
echo "  Rolling back to: $PREVIOUS_COMMIT"

# Revert the merge commit
git revert --no-commit "$MIGRATION_COMMIT"
echo "  ✓ Changes reverted (not committed yet)"
echo ""

echo "Step 2: Reinstalling MCP SDK v1.x..."
npm install "@modelcontextprotocol/sdk@^1.29.0"
npm uninstall @modelcontextprotocol/server @modelcontextprotocol/client \
  @modelcontextprotocol/express @modelcontextprotocol/node 2>/dev/null || true
echo "  ✓ Packages restored to v1.x"
echo ""

echo "Step 3: Building application..."
npm run build
if [ $? -ne 0 ]; then
  echo "  ❌ Build failed. Check TypeScript errors."
  exit 1
fi
echo "  ✓ Build successful"
echo ""

echo "Step 4: Running tests..."
npm test -- --bail 2>&1 | head -50
if [ $? -ne 0 ]; then
  echo "  ⚠️  Tests failed. Review output above."
  echo "  Continuing with deployment (tests may have pre-existing failures)"
fi
echo ""

echo "Step 5: Deploying to $CONTEXT..."
if [ "$CONTEXT" = "agent-dev" ]; then
  # Agent-dev context
  npm run brat -- bit deploy --all --context "$CONTEXT"
else
  # Staging/production
  npm run brat -- bit deploy --all --context "$CONTEXT"
fi
echo "  ✓ Deployment complete"
echo ""

echo "Step 6: Verifying service health..."
sleep 10  # Give services time to start

# Health check
SERVICES="tool-gateway llm-bot auth utility"
for service in $SERVICES; do
  if [ "$CONTEXT" = "agent-dev" ]; then
    URL="http://$service:3000/healthz"
  else
    URL="https://$service.bitbrat.io/healthz"
  fi

  HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$URL" || echo "000")
  if [ "$HTTP_CODE" = "200" ]; then
    echo "  ✓ $service healthy"
  else
    echo "  ✗ $service unhealthy (HTTP $HTTP_CODE)"
  fi
done
echo ""

echo "Step 7: Committing rollback..."
git commit -m "Rollback: MCP SDK 2.0 → v1.x

Rolled back Sprint 28 MCP SDK 2.0 migration due to critical issues in $CONTEXT.

Original commit: $MIGRATION_COMMIT
Rolled back to: $PREVIOUS_COMMIT

Reason: [TO BE FILLED]

Next steps:
- Investigate root cause
- Update migration plan
- Re-attempt after fixes

Generated by: planning/sprint-28-kbuirw/rollback.sh
"
echo "  ✓ Rollback committed"
echo ""

echo "=== Rollback Complete ==="
echo ""
echo "✅ Successfully rolled back to MCP SDK v1.x"
echo "⏱️  Time to rollback: ~3-5 minutes"
echo ""
echo "Next steps:"
echo "1. Investigate what went wrong (check logs)"
echo "2. Document findings in sprint retrospective"
echo "3. Update migration plan with fixes"
echo "4. Push rollback commit: git push"
echo ""
