import { Request, Response } from 'express';
import { McpServer } from '../common/mcp-server';

/**
 * ObsMcpServer
 * Generated by brat service bootstrap.
 */
export class ObsMcpServer extends McpServer {
  constructor() {
    super({
      serviceName: 'obs-mcp'
    });
    this.setupRoutes();
  }

  private setupRoutes() {
    const app = this.getApp();

    // Standard health check
    app.get('/health', (_req: Request, res: Response) => {
      res.status(200).json({ status: 'ok', service: 'obs-mcp' });
    });
  }

  public async close(reason: string = 'manual'): Promise<void> {
    await super.close(reason);
  }
}

if (require.main === module) {
  const server = new ObsMcpServer();
  const cfg = server.getConfig();
  server.start(cfg.port).catch((err) => {
    console.error('Failed to start obs-mcp:', err);
    process.exit(1);
  });
}
