import { Request, Response } from 'express';
import { BaseServer } from '../common/base-server';

/**
 * ObsMcpServer
 * Generated by brat service bootstrap.
 */
export class ObsMcpServer extends BaseServer {
  constructor() {
    super();
    this.setupRoutes();
  }

  private setupRoutes() {
    const app = this.getApp();

    // Standard health check
    app.get('/health', (_req: Request, res: Response) => {
      res.status(200).json({ status: 'ok', service: 'obs-mcp' });
    });
  }

  public async close(reason: string = 'manual'): Promise<void> {
    await super.close(reason);
  }
}

if (require.main === module) {
  const server = new ObsMcpServer();
  const port = parseInt(process.env.PORT || '8080', 10);
  server.start(port).catch((err) => {
    console.error('Failed to start obs-mcp:', err);
    process.exit(1);
  });
}
