import { z } from 'zod';
import { Bit } from '../common/base-server';

/**
 * ReflexServer
 * Generated by brat bit create (Sprint 331)
 * Profile: mcp-domain
 * MCP Exposure: platform+domain
 * Kind: mcp-server
 */
export class ReflexServer extends Bit {
  constructor() {
    super({ mcpExposure: 'platform+domain' });
    this.registerDomainTools();
  }

  private registerDomainTools() {
    // Example MCP tool registration
    this.registerTool(
      'echo',
      'Echoes back the input message',
      z.object({
        message: z.string().describe('The message to echo'),
      }),
      async (args) => {
        return {
          content: [{ type: 'text', text: args.message }],
        };
      }
    );

    // Add more tools here as needed
  }

  public async close(reason: string = 'manual'): Promise<void> {
    await super.close(reason);
  }
}

if (require.main === module) {
  const server = new ReflexServer();
  const port = parseInt(process.env.PORT || '3000', 10);
  server.start(port).catch((err) => {
    console.error('Failed to start reflex:', err);
    process.exit(1);
  });
}
