import { Bit } from '../common/base-server';

/**
 * TestWarningCheckServer
 * Generated by brat bit create (Sprint 331)
 * Profile: core
 * MCP Exposure: platform-only
 * Kind: pipeline-service
 */
export class TestWarningCheckServer extends Bit {
  constructor() {
    super({ mcpExposure: 'platform-only' });
  }


  public async close(reason: string = 'manual'): Promise<void> {
    await super.close(reason);
  }
}

if (require.main === module) {
  const server = new TestWarningCheckServer();
  const port = parseInt(process.env.PORT || '3000', 10);
  server.start(port).catch((err) => {
    console.error('Failed to start test-warning-check:', err);
    process.exit(1);
  });
}
