import { Request, Response } from 'express';
import { z } from 'zod';
import { McpServer } from '../common/mcp-server';

/**
 * TestSvcServer
 * Generated by brat service bootstrap.
 */
export class TestSvcServer extends McpServer {
  constructor() {
    super();
    this.setupRoutes();
  }

  private setupRoutes() {
    const app = this.getApp();

    // Standard health check
    app.get('/health', (_req: Request, res: Response) => {
      res.status(200).json({ status: 'ok', service: 'test-svc' });
    });
  }

  public async close(reason: string = 'manual'): Promise<void> {
    await super.close(reason);
  }
}

if (require.main === module) {
  const server = new TestSvcServer();
  const port = parseInt(process.env.PORT || '8080', 10);
  server.start(port).catch((err) => {
    console.error('Failed to start test-svc:', err);
    process.exit(1);
  });
}
