/**
 * derived-event.ts
 *
 * Utilities for creating derived events from existing InternalEventV2 events.
 *
 * Sprint 377: Long-Running Task Feedback
 *
 * A "derived event" is a new event created from an existing event, preserving
 * routing context (platform, channel, user, message) and establishing correlation
 * links for traceability.
 *
 * Common use cases:
 * - Progress messages: chat.progress.v1 derived from original request
 * - Error notifications: chat.error.v1 derived from failed operation
 * - Status updates: chat.status.v1 derived from long-running task
 * - Confirmation prompts: chat.confirm.v1 derived from user action
 *
 * Usage:
 * ```typescript
 * const progressEvent = createDerivedEvent(originalEvent, {
 *   type: 'chat.progress.v1',
 *   annotations: [
 *     { kind: 'progress_context', value: { stage: 'initial', ... } },
 *     { kind: 'prompt', value: 'Generate progress message...' },
 *   ],
 * });
 *
 * await messageBus.publish('internal.ingress.v1', progressEvent);
 * ```
 */

import { randomUUID } from 'crypto';
import type { InternalEventV2, AnnotationV1, Routing } from '../../types/events';

/**
 * Options for creating a derived event.
 */
export interface DerivedEventOptions {
  /**
   * Event type for the derived event.
   * Examples: 'chat.progress.v1', 'chat.error.v1', 'chat.status.v1'
   */
  type: string;

  /**
   * Additional annotations to add to the derived event.
   * These supplement the automatic derived_from annotation.
   */
  annotations?: AnnotationV1[];

  /**
   * Override the message field (if not provided, copies from original).
   * Set to null to clear the message field.
   */
  message?: InternalEventV2['message'] | null;

  /**
   * Override the payload (if not provided, creates minimal payload with type).
   */
  payload?: Record<string, any>;

  /**
   * Override QoS settings (if not provided, copies from original).
   */
  qos?: InternalEventV2['qos'];

  /**
   * Override ingress (if not provided, copies from original).
   */
  ingress?: InternalEventV2['ingress'];

  /**
   * Override identity (if not provided, copies from original).
   */
  identity?: InternalEventV2['identity'];

  /**
   * Override egress (if not provided, copies from original).
   */
  egress?: InternalEventV2['egress'];

  /**
   * Source service creating the derived event (for provenance).
   * Example: 'feedback-middleware', 'error-handler', 'timeout-watcher'
   */
  source: string;
}

/**
 * Create a derived event from an existing InternalEventV2.
 *
 * Preserves routing context (platform, channel, user, message) and adds
 * correlation tracking via derived_from annotation.
 *
 * @param originalEvent - The source event to derive from
 * @param options - Derived event configuration
 * @returns New InternalEventV2 with correlation tracking
 *
 * @example
 * // Progress message
 * const progressEvent = createDerivedEvent(originalEvent, {
 *   type: 'chat.progress.v1',
 *   source: 'feedback-middleware',
 *   annotations: [
 *     { kind: 'progress_context', value: { stage: 'initial' }, ... },
 *     { kind: 'prompt', value: 'Generate progress message...', ... },
 *   ],
 * });
 *
 * @example
 * // Error notification
 * const errorEvent = createDerivedEvent(originalEvent, {
 *   type: 'chat.error.v1',
 *   source: 'error-handler',
 *   message: null,  // Clear message, will be generated by llm-bot
 *   annotations: [
 *     { kind: 'error_context', value: { code: 'TIMEOUT', ... }, ... },
 *     { kind: 'prompt', value: 'Generate user-friendly error message...', ... },
 *   ],
 * });
 */
export function createDerivedEvent(
  originalEvent: InternalEventV2,
  options: DerivedEventOptions
): InternalEventV2 {
  // Generate new identifiers for derived event
  const correlationId = randomUUID();
  const timestamp = new Date().toISOString();

  // Create derived_from annotation for traceability
  const derivedFromAnnotation: AnnotationV1 = {
    kind: 'derived_from',
    value: JSON.stringify({
      correlationId: originalEvent.correlationId,
      type: originalEvent.type,
      source: options.source,
      derivedAt: timestamp,
    }),
    source: options.source,
    id: randomUUID(),
    createdAt: timestamp,
  };

  // Combine annotations: derived_from + custom annotations
  const annotations: AnnotationV1[] = [
    derivedFromAnnotation,
    ...(options.annotations || []),
  ];

  // Determine message field
  let message: InternalEventV2['message'];
  if (options.message === null) {
    // Explicitly cleared
    message = undefined;
  } else if (options.message !== undefined) {
    // Explicitly provided
    message = options.message;
  } else {
    // Default: copy from original (provides context for llm-bot)
    message = originalEvent.message;
  }

  // Build routing object (InternalEventV2 requires full Routing, not just stage)
  const routing: Routing = {
    stage: 'initial',  // All derived events start at initial stage
    slip: [],          // Empty slip, event-router will populate
    history: [],       // Empty history
  };

  // Build derived event
  const derivedEvent: InternalEventV2 = {
    // Version
    v: '2',

    // New identifiers
    correlationId,

    // Event type (at root level)
    type: options.type as any,  // Type assertion for string literal compatibility

    // Routing context (CRITICAL: copy from original for proper delivery)
    ingress: options.ingress || originalEvent.ingress,
    identity: options.identity || originalEvent.identity,
    egress: options.egress || originalEvent.egress,

    // Message context (copy from original unless overridden)
    message,

    // Payload (minimal by default - empty object)
    payload: options.payload !== undefined ? options.payload : {},

    // QoS (copy from original unless overridden)
    qos: options.qos !== undefined ? options.qos : originalEvent.qos,

    // Annotations (derived_from + custom)
    annotations,

    // Routing (starts at initial stage with empty slip)
    routing,
  };

  return derivedEvent;
}

/**
 * Extract the original event's correlationId from a derived event.
 *
 * Traverses the chain of derived_from annotations to find the root event.
 *
 * @param event - Event to inspect (may be derived)
 * @returns Original correlationId, or the event's own correlationId if not derived
 *
 * @example
 * const originalCorrelationId = getOriginalCorrelationId(progressEvent);
 * logger.info('Progress for request', { originalCorrelationId });
 */
export function getOriginalCorrelationId(event: InternalEventV2): string {
  const derivedFrom = event.annotations?.find((a) => a.kind === 'derived_from');

  if (derivedFrom && derivedFrom.value) {
    try {
      const parsed = JSON.parse(derivedFrom.value);
      if (parsed.correlationId) {
        return parsed.correlationId;
      }
    } catch {
      // Invalid JSON, fall through
    }
  }

  // Not derived, or missing annotation - return own correlationId
  return event.correlationId;
}

/**
 * Check if an event is a derived event.
 *
 * @param event - Event to check
 * @returns true if event has derived_from annotation
 *
 * @example
 * if (isDerivedEvent(event)) {
 *   logger.debug('Derived event', {
 *     type: event.type,
 *     originalCorrelationId: getOriginalCorrelationId(event),
 *   });
 * }
 */
export function isDerivedEvent(event: InternalEventV2): boolean {
  return !!event.annotations?.some((a) => a.kind === 'derived_from');
}

/**
 * Get the derivation chain for an event.
 *
 * Returns array of correlation IDs from root event to current event.
 *
 * @param event - Event to inspect
 * @returns Array of correlationIds in chronological order (oldest first)
 *
 * @example
 * const chain = getDerivationChain(event);
 * // ['abc123', 'def456', 'ghi789']  // Original → Progress → Update
 * logger.info('Derivation chain', { chain, depth: chain.length });
 */
export function getDerivationChain(event: InternalEventV2): string[] {
  const chain: string[] = [];

  // Walk up the derivation chain (limit to 10 levels to prevent infinite loops)
  const derivedFrom = event.annotations?.find((a) => a.kind === 'derived_from');

  if (derivedFrom && derivedFrom.value) {
    try {
      const parsed = JSON.parse(derivedFrom.value);
      if (parsed.correlationId) {
        chain.unshift(parsed.correlationId);  // Add original to front
        // Note: We can't continue walking without the original event object
        // This would require event store lookup, out of scope for this utility
      }
    } catch {
      // Invalid JSON, ignore
    }
  }

  // Add current event's correlationId
  chain.push(event.correlationId);

  return chain;
}

/**
 * Common derived event types.
 *
 * Standardized type strings for platform-wide derived events.
 */
export const DerivedEventTypes = {
  /** Progress update during long-running operation */
  PROGRESS: 'chat.progress.v1',

  /** Error notification for failed operation */
  ERROR: 'chat.error.v1',

  /** Status update for background task */
  STATUS: 'chat.status.v1',

  /** Confirmation prompt for user action */
  CONFIRM: 'chat.confirm.v1',

  /** Timeout warning for approaching deadline */
  TIMEOUT_WARNING: 'chat.timeout.v1',

  /** Cancellation acknowledgment */
  CANCELLED: 'chat.cancelled.v1',
} as const;

/**
 * Helper to create a progress event (most common derived event type).
 *
 * Convenience wrapper around createDerivedEvent for progress messages.
 *
 * @param originalEvent - Source event
 * @param stage - Progress stage ('initial' | 'update' | 'timeout' | 'completion')
 * @param progressContext - Progress context data
 * @param prompt - Instructions for llm-bot
 * @param source - Source service (default: 'feedback-middleware')
 * @returns Derived progress event
 *
 * @example
 * const progressEvent = createProgressEvent(
 *   originalEvent,
 *   'initial',
 *   { operation: 'image_generation', parameters: { prompt: '...' }, elapsedMs: 5000 },
 *   'Generate brief progress message...',
 *   'feedback-middleware'
 * );
 */
export function createProgressEvent(
  originalEvent: InternalEventV2,
  stage: 'initial' | 'update' | 'timeout' | 'completion',
  progressContext: Record<string, any>,
  prompt: string,
  source: string = 'feedback-middleware'
): InternalEventV2 {
  const timestamp = new Date().toISOString();

  return createDerivedEvent(originalEvent, {
    type: DerivedEventTypes.PROGRESS,
    source,
    annotations: [
      {
        kind: 'progress_context',
        value: JSON.stringify({
          originalCorrelationId: originalEvent.correlationId,
          originalMessage: originalEvent.message?.text || '',
          stage,
          ...progressContext,
        }),
        source,
        id: randomUUID(),
        createdAt: timestamp,
      },
      {
        kind: 'prompt',
        value: prompt,
        source,
        id: randomUUID(),
        createdAt: timestamp,
      },
    ],
  });
}
