/**
 * Unit tests for candidate-builder.ts
 */

import { describe, it, expect } from '@jest/globals';
import {
  buildCandidate,
  validateCandidateTemplate,
  extractCandidateTemplatePaths,
} from '../candidate-builder.js';
import type { InternalEventV2 } from '../../../types/events.js';
import type { Reflex } from '../../../types/reflex.js';

describe('Candidate Builder', () => {
  const mockReflex: Reflex = {
    id: 'reflex-123',
    name: 'Test Reflex',
    active: true,
    priority: 1,
    match: {
      type: 'exact',
      pattern: '!fail',
      field: 'message.text',
    },
    action: {
      tool: 'obs.set_source_visibility',
      parameters: {
        sourceName: 'FailOverlay',
        visible: true,
      },
    },
    createdAt: '2026-07-04T12:00:00Z',
    updatedAt: '2026-07-04T12:00:00Z',
  };

  const mockEvent: InternalEventV2 = {
    v: '2',
    eventType: 'twitch.chat.message',
    correlationId: 'test-123',
    traceId: 'trace-123',
    source: 'twitch-ingress',
    ingress: {
      ingressAt: '2026-07-04T12:00:00Z',
      source: 'twitch-ingress',
      connector: 'twitch',
    },
    message: {
      id: 'msg-123',
      role: 'user',
      text: '!fail',
    },
    identity: {
      platform: { id: 'twitch', name: 'Twitch' },
      externalUser: { id: 'user123', displayName: 'TestUser' },
      user: {
        id: 'user-123',
        displayName: 'TestUser',
      },
    },
  };

  const mockToolResult = {
    visible: true,
    sourceName: 'FailOverlay',
  };

  describe('buildCandidate', () => {
    it('should build candidate with event fields', () => {
      const template = 'Command executed by {{event.identity.user.displayName}}';
      const candidate = buildCandidate(template, mockReflex, mockEvent, mockToolResult);

      expect(candidate.kind).toBe('text');
      expect(candidate.source).toBe('reflex');
      expect(candidate.text).toBe('Command executed by TestUser');
      expect(candidate.status).toBe('proposed');
      expect(candidate.priority).toBe(0);
      expect(candidate.confidence).toBe(1.0);
    });

    it('should build candidate with result fields', () => {
      const template = 'Overlay visibility: {{result.visible}}';
      const candidate = buildCandidate(template, mockReflex, mockEvent, mockToolResult);

      expect(candidate.text).toBe('Overlay visibility: true');
    });

    it('should build candidate with both event and result fields', () => {
      const template = '{{event.identity.user.displayName}} toggled {{result.sourceName}} to {{result.visible}}';
      const candidate = buildCandidate(template, mockReflex, mockEvent, mockToolResult);

      expect(candidate.text).toBe('TestUser toggled FailOverlay to true');
    });

    it('should include reflex metadata', () => {
      const template = 'Test';
      const candidate = buildCandidate(template, mockReflex, mockEvent, mockToolResult);

      expect(candidate.metadata).toBeDefined();
      expect(candidate.metadata!.reflexId).toBe('reflex-123');
      expect(candidate.metadata!.reflexName).toBe('Test Reflex');
      expect(candidate.metadata!.reflexPriority).toBe(1);
    });

    it('should set reason field', () => {
      const template = 'Test';
      const candidate = buildCandidate(template, mockReflex, mockEvent, mockToolResult);

      expect(candidate.reason).toBe('Generated by reflex: Test Reflex');
    });

    it('should generate unique IDs', () => {
      const template = 'Test';
      const candidate1 = buildCandidate(template, mockReflex, mockEvent, mockToolResult);
      const candidate2 = buildCandidate(template, mockReflex, mockEvent, mockToolResult);

      expect(candidate1.id).not.toBe(candidate2.id);
    });

    it('should handle missing event fields gracefully', () => {
      const template = 'Missing: {{event.missing.field}}';
      const candidate = buildCandidate(template, mockReflex, mockEvent, mockToolResult);

      expect(candidate.text).toBe('Missing: {{event.missing.field}}');
    });

    it('should handle missing result fields gracefully', () => {
      const template = 'Missing: {{result.missing}}';
      const candidate = buildCandidate(template, mockReflex, mockEvent, mockToolResult);

      expect(candidate.text).toBe('Missing: {{result.missing}}');
    });

    it('should handle complex nested paths', () => {
      const template = 'Platform: {{event.identity.platform.name}}';
      const candidate = buildCandidate(template, mockReflex, mockEvent, mockToolResult);

      expect(candidate.text).toBe('Platform: Twitch');
    });

    it('should handle templates with no placeholders', () => {
      const template = 'Static message';
      const candidate = buildCandidate(template, mockReflex, mockEvent, mockToolResult);

      expect(candidate.text).toBe('Static message');
    });

    it('should set format to plain', () => {
      const template = 'Test';
      const candidate = buildCandidate(template, mockReflex, mockEvent, mockToolResult);

      expect(candidate.format).toBe('plain');
    });

    it('should set createdAt timestamp', () => {
      const template = 'Test';
      const before = new Date().toISOString();
      const candidate = buildCandidate(template, mockReflex, mockEvent, mockToolResult);
      const after = new Date().toISOString();

      expect(candidate.createdAt).toMatch(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/);
      expect(candidate.createdAt >= before && candidate.createdAt <= after).toBe(true);
    });
  });

  describe('validateCandidateTemplate', () => {
    it('should validate template with event prefix', () => {
      const result = validateCandidateTemplate('Hello {{event.user.name}}');
      expect(result.isValid).toBe(true);
    });

    it('should validate template with result prefix', () => {
      const result = validateCandidateTemplate('Result: {{result.status}}');
      expect(result.isValid).toBe(true);
    });

    it('should validate template with both prefixes', () => {
      const result = validateCandidateTemplate('{{event.user}} got {{result.points}} points');
      expect(result.isValid).toBe(true);
    });

    it('should reject placeholder without event or result prefix', () => {
      const result = validateCandidateTemplate('Invalid: {{user.name}}');
      expect(result.isValid).toBe(false);
      expect(result.errors).toBeDefined();
      expect(result.errors![0]).toContain('event.');
      expect(result.errors![0]).toContain('result.');
    });

    it('should detect unmatched braces', () => {
      const result = validateCandidateTemplate('{{event.user.name');
      expect(result.isValid).toBe(false);
      expect(result.errors![0]).toContain('Unmatched braces');
    });

    it('should detect empty placeholders', () => {
      const result = validateCandidateTemplate('Empty: {{}}');
      expect(result.isValid).toBe(false);
      expect(result.errors![0]).toContain('Empty placeholder');
    });

    it('should validate templates with escaped braces', () => {
      const result = validateCandidateTemplate('{{event.name}} and \\{\\{literal\\}\\}');
      expect(result.isValid).toBe(true);
    });

    it('should validate empty templates', () => {
      const result = validateCandidateTemplate('');
      expect(result.isValid).toBe(true);
    });

    it('should validate templates with no placeholders', () => {
      const result = validateCandidateTemplate('Static text');
      expect(result.isValid).toBe(true);
    });
  });

  describe('extractCandidateTemplatePaths', () => {
    it('should extract event paths', () => {
      const result = extractCandidateTemplatePaths('{{event.user.name}} and {{event.message.text}}');
      expect(result.eventPaths).toEqual(['user.name', 'message.text']);
      expect(result.resultPaths).toEqual([]);
    });

    it('should extract result paths', () => {
      const result = extractCandidateTemplatePaths('{{result.status}} {{result.count}}');
      expect(result.eventPaths).toEqual([]);
      expect(result.resultPaths).toEqual(['status', 'count']);
    });

    it('should extract both event and result paths', () => {
      const result = extractCandidateTemplatePaths('{{event.user}} got {{result.points}}');
      expect(result.eventPaths).toEqual(['user']);
      expect(result.resultPaths).toEqual(['points']);
    });

    it('should handle templates with no placeholders', () => {
      const result = extractCandidateTemplatePaths('No placeholders');
      expect(result.eventPaths).toEqual([]);
      expect(result.resultPaths).toEqual([]);
    });

    it('should handle nested paths', () => {
      const result = extractCandidateTemplatePaths('{{event.identity.user.displayName}}');
      expect(result.eventPaths).toEqual(['identity.user.displayName']);
    });

    it('should trim whitespace', () => {
      const result = extractCandidateTemplatePaths('{{ event.user.name }}');
      expect(result.eventPaths).toEqual(['user.name']);
    });
  });

  describe('Edge cases', () => {
    it('should handle object result values', () => {
      const template = 'Result: {{result.obj}}';
      const result = { obj: { a: 1, b: 2 } };
      const candidate = buildCandidate(template, mockReflex, mockEvent, result);

      expect(candidate.text).toBe('Result: {"a":1,"b":2}');
    });

    it('should handle array result values', () => {
      const template = 'Items: {{result.items}}';
      const result = { items: [1, 2, 3] };
      const candidate = buildCandidate(template, mockReflex, mockEvent, result);

      expect(candidate.text).toBe('Items: [1,2,3]');
    });

    it('should handle number result values', () => {
      const template = 'Count: {{result.count}}';
      const result = { count: 42 };
      const candidate = buildCandidate(template, mockReflex, mockEvent, result);

      expect(candidate.text).toBe('Count: 42');
    });

    it('should handle boolean result values', () => {
      const template = 'Success: {{result.success}}';
      const result = { success: false };
      const candidate = buildCandidate(template, mockReflex, mockEvent, result);

      expect(candidate.text).toBe('Success: false');
    });
  });
});
