/**
 * Candidate Builder for Reflex Bit
 *
 * Generates candidate responses from templates with dual-context interpolation:
 * - {{event.field.path}} - Access event data
 * - {{result.field.path}} - Access MCP tool call results
 *
 * Example:
 * Template: "Fail overlay activated by {{event.identity.user.displayName}}! Status: {{result.visible}}"
 * Event: { identity: { user: { displayName: 'JohnDoe' } } }
 * Result: { visible: true }
 * Output: "Fail overlay activated by JohnDoe! Status: true"
 */

import { v4 as uuidv4 } from 'uuid';
import { logger } from '../../common/logging';
import { CandidateV1, InternalEventV2 } from '../../types/events.js';
import { Reflex } from '../../types/reflex.js';
import { getFieldValue } from './field-accessor.js';

/**
 * Builds a candidate response from a template with dual-context interpolation.
 *
 * Process:
 * 1. Parse template for {{event.path}} and {{result.path}} placeholders
 * 2. Replace {{event.path}} with values from event
 * 3. Replace {{result.path}} with values from tool result
 * 4. Build CandidateV1 object with source='reflex'
 *
 * @param template - Template string with {{event.path}} and {{result.path}} placeholders
 * @param reflex - Reflex that generated this candidate (for metadata)
 * @param event - Event being processed
 * @param toolResult - Result from MCP tool execution
 * @returns CandidateV1 object ready to add to event.candidates
 *
 * @example
 * const template = "Command executed by {{event.identity.user.displayName}}! Result: {{result.status}}";
 * const event = { identity: { user: { displayName: 'JohnDoe' } } };
 * const result = { status: 'success' };
 *
 * buildCandidate(template, reflex, event, result)
 * // {
 * //   id: '...',
 * //   kind: 'text',
 * //   source: 'reflex',
 * //   text: 'Command executed by JohnDoe! Result: success',
 * //   confidence: 1.0,
 * //   ...
 * // }
 */
export function buildCandidate(
  template: string,
  reflex: Reflex,
  event: InternalEventV2,
  toolResult: any
): CandidateV1 {
  // Interpolate template with dual context
  const text = interpolateDualContext(template, event, toolResult);

  // Build CandidateV1 object
  const candidate: CandidateV1 = {
    id: uuidv4(),
    kind: 'text',
    source: 'reflex',
    createdAt: new Date().toISOString(),
    status: 'proposed',
    priority: 0, // Reflex candidates have highest priority
    confidence: 1.0, // Deterministic, so confidence is 1.0
    text,
    format: 'plain',
    reason: `Generated by reflex: ${reflex.name}`,
    metadata: {
      reflexId: reflex.id,
      reflexName: reflex.name,
      reflexPriority: reflex.priority,
    },
  };

  return candidate;
}

/**
 * Interpolates a template with dual context (event + result).
 *
 * Supports two placeholder formats:
 * - {{event.field.path}} - Extracts from event object
 * - {{result.field.path}} - Extracts from tool result
 *
 * @param template - Template string with placeholders
 * @param event - Event object for {{event.path}}
 * @param toolResult - Tool result for {{result.path}}
 * @returns Interpolated string
 */
function interpolateDualContext(template: string, event: InternalEventV2, toolResult: any): string {
  let result = template;

  // Replace {{event.path}} placeholders
  result = result.replace(/\{\{event\.([^}]+)\}\}/g, (match, path) => {
    const value = getFieldValue(event, path.trim());
    return stringifyValue(value, match);
  });

  // Replace {{result.path}} placeholders
  result = result.replace(/\{\{result\.([^}]+)\}\}/g, (match, path) => {
    const value = getFieldValue(toolResult, path.trim());
    return stringifyValue(value, match);
  });

  // Handle escaped braces
  result = result.replace(/\\(\{\{|\}\})/g, '$1');

  return result;
}

/**
 * Converts a value to a string for template interpolation.
 *
 * @param value - Value to stringify
 * @param fallback - Fallback string if value is undefined/null
 * @returns String representation
 */
function stringifyValue(value: any, fallback: string): string {
  if (value === undefined || value === null) {
    logger.warn(`[candidate-builder] Missing field in template: ${fallback} (keeping placeholder)`);
    return fallback; // Keep placeholder if field missing
  }

  if (typeof value === 'string') {
    return value;
  }

  if (typeof value === 'number' || typeof value === 'boolean') {
    return String(value);
  }

  if (typeof value === 'object') {
    try {
      return JSON.stringify(value);
    } catch (error) {
      logger.warn('candidate.builder.stringify_error', { error: error instanceof Error ? error.message : String(error) });
      return '[object]';
    }
  }

  return String(value);
}

/**
 * Validates a candidate template for syntax.
 *
 * Checks:
 * - Valid placeholder syntax
 * - Uses event. or result. prefixes
 * - No unmatched braces
 *
 * @param template - Template to validate
 * @returns Validation result
 *
 * @example
 * validateCandidateTemplate("Hi {{event.user.name}}!")
 * // { isValid: true }
 *
 * validateCandidateTemplate("Hi {{user.name}}!")
 * // { isValid: false, errors: ['Placeholder must use event. or result. prefix'] }
 */
export function validateCandidateTemplate(template: string): {
  isValid: boolean;
  errors?: string[];
} {
  const errors: string[] = [];

  // Check for placeholders without event. or result. prefix
  const invalidPlaceholders = template.match(/\{\{(?!event\.|result\.)([^}]+)\}\}/g);
  if (invalidPlaceholders) {
    errors.push(
      `Placeholders must use "event." or "result." prefix. Found: ${invalidPlaceholders.join(', ')}`
    );
  }

  // Check for unmatched braces
  const openCount = (template.match(/(?<!\\)\{\{/g) || []).length;
  const closeCount = (template.match(/(?<!\\)\}\}/g) || []).length;

  if (openCount !== closeCount) {
    errors.push(`Unmatched braces (${openCount} opening, ${closeCount} closing)`);
  }

  // Check for empty placeholders
  if (/(?<!\\)\{\{\s*\}\}/.test(template)) {
    errors.push('Empty placeholder {{}} found');
  }

  return {
    isValid: errors.length === 0,
    ...(errors.length > 0 && { errors }),
  };
}

/**
 * Extracts field paths referenced in a candidate template.
 *
 * Returns two arrays: one for event paths, one for result paths.
 *
 * @param template - Template string
 * @returns Object with eventPaths and resultPaths arrays
 *
 * @example
 * extractCandidateTemplatePaths("{{event.user.name}} got {{result.points}} points")
 * // {
 * //   eventPaths: ['user.name'],
 * //   resultPaths: ['points']
 * // }
 */
export function extractCandidateTemplatePaths(template: string): {
  eventPaths: string[];
  resultPaths: string[];
} {
  const eventPaths: string[] = [];
  const resultPaths: string[] = [];

  // Extract {{event.path}} placeholders
  const eventMatches = template.matchAll(/\{\{event\.([^}]+)\}\}/g);
  for (const match of eventMatches) {
    eventPaths.push(match[1].trim());
  }

  // Extract {{result.path}} placeholders
  const resultMatches = template.matchAll(/\{\{result\.([^}]+)\}\}/g);
  for (const match of resultMatches) {
    resultPaths.push(match[1].trim());
  }

  return { eventPaths, resultPaths };
}
