/**
 * Candidate Builder for Reflex Bit
 *
 * Generates candidate responses from templates with dual-context interpolation:
 * - {{event.field.path}} - Access event data
 * - {{result.field.path}} - Access MCP tool call results
 *
 * Example:
 * Template: "Fail overlay activated by {{event.identity.user.displayName}}! Status: {{result.visible}}"
 * Event: { identity: { user: { displayName: 'JohnDoe' } } }
 * Result: { visible: true }
 * Output: "Fail overlay activated by JohnDoe! Status: true"
 */

import { v4 as uuidv4 } from 'uuid';
import { logger } from '../../common/logging';
import { CandidateV1, InternalEventV2 } from '../../types/events.js';
import { Reflex } from '../../types/reflex.js';
import { getFieldValue } from './field-accessor.js';

/**
 * Builds candidate(s) from template(s) with dual-context interpolation.
 *
 * Process:
 * 1. Parse template(s) for {{event.path}} and {{result.path}} placeholders
 * 2. Replace {{event.path}} with values from event
 * 3. Replace {{result.path}} with values from tool result
 * 4. Build CandidateV1 object(s) with source='reflex'
 *
 * @param templates - Single template string or array of template strings
 * @param reflex - Reflex that generated these candidates (for metadata)
 * @param event - Event being processed
 * @param toolResult - Result from MCP tool execution
 * @returns Array of CandidateV1 objects ready to add to event.candidates
 *
 * @example Single template
 * const template = "Command executed by {{event.identity.user.displayName}}! Result: {{result.status}}";
 * buildCandidates(template, reflex, event, result)
 * // [{ id: '...', text: 'Command executed by JohnDoe! Result: success', ... }]
 *
 * @example Multiple templates
 * const templates = ["Pong!", "Pong from {{event.identity.user.displayName}}!"];
 * buildCandidates(templates, reflex, event, result)
 * // [
 * //   { id: '...', text: 'Pong!', ... },
 * //   { id: '...', text: 'Pong from JohnDoe!', ... }
 * // ]
 */
export function buildCandidates(
  templates: string | string[],
  reflex: Reflex,
  event: InternalEventV2,
  toolResult: any
): CandidateV1[] {
  // Normalize to array
  const templateArray = Array.isArray(templates) ? templates : [templates];

  // Build a candidate for each template
  return templateArray.map((template) => {
    const text = interpolateDualContext(template, event, toolResult);

    const candidate: CandidateV1 = {
      id: uuidv4(),
      kind: 'text',
      source: 'reflex',
      createdAt: new Date().toISOString(),
      status: 'proposed',
      priority: 0, // Reflex candidates have highest priority
      confidence: 1.0, // Deterministic, so confidence is 1.0
      text,
      format: 'plain',
      reason: `Generated by reflex: ${reflex.name}`,
      metadata: {
        reflexId: reflex.id,
        reflexName: reflex.name,
        reflexPriority: reflex.priority,
      },
    };

    return candidate;
  });
}

/**
 * Legacy function - builds a single candidate from a single template.
 * @deprecated Use buildCandidates() instead for consistency.
 */
export function buildCandidate(
  template: string,
  reflex: Reflex,
  event: InternalEventV2,
  toolResult: any
): CandidateV1 {
  return buildCandidates(template, reflex, event, toolResult)[0];
}

/**
 * Interpolates a template with dual context (event + result).
 *
 * Supports two placeholder formats:
 * - {{event.field.path}} - Extracts from event object
 * - {{result.field.path}} - Extracts from tool result
 *
 * @param template - Template string with placeholders
 * @param event - Event object for {{event.path}}
 * @param toolResult - Tool result for {{result.path}}
 * @returns Interpolated string
 */
function interpolateDualContext(template: string, event: InternalEventV2, toolResult: any): string {
  let result = template;

  // Replace {{event.path}} placeholders
  result = result.replace(/\{\{event\.([^}]+)\}\}/g, (match, path) => {
    const value = getFieldValue(event, path.trim());
    return stringifyValue(value, match);
  });

  // Replace {{result.path}} placeholders
  result = result.replace(/\{\{result\.([^}]+)\}\}/g, (match, path) => {
    const value = getFieldValue(toolResult, path.trim());
    return stringifyValue(value, match);
  });

  // Handle escaped braces
  result = result.replace(/\\(\{\{|\}\})/g, '$1');

  return result;
}

/**
 * Converts a value to a string for template interpolation.
 *
 * @param value - Value to stringify
 * @param fallback - Fallback string if value is undefined/null
 * @returns String representation
 */
function stringifyValue(value: any, fallback: string): string {
  if (value === undefined || value === null) {
    logger.warn(`[candidate-builder] Missing field in template: ${fallback} (keeping placeholder)`);
    return fallback; // Keep placeholder if field missing
  }

  if (typeof value === 'string') {
    return value;
  }

  if (typeof value === 'number' || typeof value === 'boolean') {
    return String(value);
  }

  if (typeof value === 'object') {
    try {
      return JSON.stringify(value);
    } catch (error) {
      logger.warn('candidate.builder.stringify_error', { error: error instanceof Error ? error.message : String(error) });
      return '[object]';
    }
  }

  return String(value);
}

/**
 * Validates a candidate template for syntax.
 *
 * Checks:
 * - Valid placeholder syntax
 * - Uses event. or result. prefixes
 * - No unmatched braces
 *
 * @param template - Template to validate
 * @returns Validation result
 *
 * @example
 * validateCandidateTemplate("Hi {{event.user.name}}!")
 * // { isValid: true }
 *
 * validateCandidateTemplate("Hi {{user.name}}!")
 * // { isValid: false, errors: ['Placeholder must use event. or result. prefix'] }
 */
export function validateCandidateTemplate(template: string): {
  isValid: boolean;
  errors?: string[];
} {
  const errors: string[] = [];

  // Check for placeholders without event. or result. prefix
  const invalidPlaceholders = template.match(/\{\{(?!event\.|result\.)([^}]+)\}\}/g);
  if (invalidPlaceholders) {
    errors.push(
      `Placeholders must use "event." or "result." prefix. Found: ${invalidPlaceholders.join(', ')}`
    );
  }

  // Check for unmatched braces
  const openCount = (template.match(/(?<!\\)\{\{/g) || []).length;
  const closeCount = (template.match(/(?<!\\)\}\}/g) || []).length;

  if (openCount !== closeCount) {
    errors.push(`Unmatched braces (${openCount} opening, ${closeCount} closing)`);
  }

  // Check for empty placeholders
  if (/(?<!\\)\{\{\s*\}\}/.test(template)) {
    errors.push('Empty placeholder {{}} found');
  }

  return {
    isValid: errors.length === 0,
    ...(errors.length > 0 && { errors }),
  };
}

/**
 * Extracts field paths referenced in a candidate template.
 *
 * Returns two arrays: one for event paths, one for result paths.
 *
 * @param template - Template string
 * @returns Object with eventPaths and resultPaths arrays
 *
 * @example
 * extractCandidateTemplatePaths("{{event.user.name}} got {{result.points}} points")
 * // {
 * //   eventPaths: ['user.name'],
 * //   resultPaths: ['points']
 * // }
 */
export function extractCandidateTemplatePaths(template: string): {
  eventPaths: string[];
  resultPaths: string[];
} {
  const eventPaths: string[] = [];
  const resultPaths: string[] = [];

  // Extract {{event.path}} placeholders (with optional whitespace)
  const eventMatches = template.matchAll(/\{\{\s*event\.([^}]+?)\s*\}\}/g);
  for (const match of eventMatches) {
    eventPaths.push(match[1].trim());
  }

  // Extract {{result.path}} placeholders (with optional whitespace)
  const resultMatches = template.matchAll(/\{\{\s*result\.([^}]+?)\s*\}\}/g);
  for (const match of resultMatches) {
    resultPaths.push(match[1].trim());
  }

  return { eventPaths, resultPaths };
}
