defaultService: https://www.googleapis.com/compute/v1/projects/bitbrat-local/global/backendServices/be-default
hostRules:
  - hosts:
      - api.bitbrat.ai
    pathMatcher: default-matcher
name: bitbrat-global-url-map
pathMatchers:
  - defaultService: https://www.googleapis.com/compute/v1/projects/bitbrat-local/global/backendServices/be-default
    name: default-matcher
    routeRules:
      - matchRules:
          - prefixMatch: /assets
        priority: 1
        routeAction:
          weightedBackendServices:
            - backendService: https://www.googleapis.com/compute/v1/projects/bitbrat-local/global/backendServices/be-default
              weight: 100
      - matchRules:
          - prefixMatch: /oauth
        priority: 2
        routeAction:
          weightedBackendServices:
            - backendService: https://www.googleapis.com/compute/v1/projects/bitbrat-local/global/backendServices/be-oauth-flow
              weight: 100
      - matchRules:
          - prefixMatch: /_debug/ingress/twitch
        priority: 3
        routeAction:
          urlRewrite:
            pathPrefixRewrite: /_debug/twitch
          weightedBackendServices:
            - backendService: https://www.googleapis.com/compute/v1/projects/bitbrat-local/global/backendServices/be-ingress-egress
              weight: 100
