defaultService: https://www.googleapis.com/compute/v1/projects/bitbrat-local/global/backendServices/be-assets-proxy
hostRules:
  - hosts:
      - api.dev.bitbrat.ai
    pathMatcher: default-matcher
name: bitbrat-global-url-map
pathMatchers:
  - defaultService: https://www.googleapis.com/compute/v1/projects/bitbrat-local/global/backendServices/be-assets-proxy
    name: default-matcher
    routeRules:
      - matchRules:
          - prefixMatch: /assets
        priority: 1
        routeAction:
          urlRewrite:
            pathPrefixRewrite: /bucket/default-content-bucket
          weightedBackendServices:
            - backendService: https://www.googleapis.com/compute/v1/projects/bitbrat-local/global/backendServices/be-assets-proxy
              weight: 100
      - matchRules:
          - prefixMatch: /oauth
        priority: 2
        routeAction:
          weightedBackendServices:
            - backendService: https://www.googleapis.com/compute/v1/projects/bitbrat-local/global/backendServices/be-oauth-flow
              weight: 100
      - matchRules:
          - prefixMatch: /_debug/ingress/twitch
        priority: 3
        routeAction:
          urlRewrite:
            pathPrefixRewrite: /_debug/twitch
          weightedBackendServices:
            - backendService: https://www.googleapis.com/compute/v1/projects/bitbrat-local/global/backendServices/be-ingress-egress
              weight: 100
      - matchRules:
          - prefixMatch: /_debug/ingress/config
        priority: 4
        routeAction:
          urlRewrite:
            pathPrefixRewrite: /_debug/config
          weightedBackendServices:
            - backendService: https://www.googleapis.com/compute/v1/projects/bitbrat-local/global/backendServices/be-ingress-egress
              weight: 100
      - matchRules:
          - prefixMatch: /_debug/llm/mcp
        priority: 5
        routeAction:
          urlRewrite:
            pathPrefixRewrite: /_debug/mcp
          weightedBackendServices:
            - backendService: https://www.googleapis.com/compute/v1/projects/bitbrat-local/global/backendServices/be-llm-bot
              weight: 100
